# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.0.2'
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '/p:SkipInvalidConfigurations=true /t:Pack /p:Configuration=$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/$(system.teamProject)/bin/$(buildConfiguration)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'd7472998-0430-48de-a9c9-5c4045e5debe'

- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'Zettersten'
    repositoryName: 'Zettersten/Tsys.net'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'manual'
    tag: 'v$(Build.BuildNumber)'
    title: 'v$(Build.BuildNumber)'
    assets: '$(Build.ArtifactStagingDirectory)/$(system.teamProject)/bin/$(buildConfiguration)/*'
